### ISSUE TITLE
ptt_all_post.py CLI interface

### ISSUE THREAD

**Issue by poga** [AmberFu/ptt_crawler#1]
能替 `ptt_all_post.py` 這個檔案提供從 terminal 操作的 CLI 介面嗎？希望可以用以下的指令格式執行：

```
python ptt_all_post.py <要爬的日期> <輸出的檔案路徑>
```

譬如說我想抓 ALL_POST 裡 9/20 的文章標題就輸入 

```
python ptt_all_post.py 2017/09/20 ~/all_post.csv
```

也許可以參考 [這裡](https://www.tutorialspoint.com/python/python_command_line_arguments.htm) 的作法

**Comment by AmberFu** [comment]
好的，我研究看看，完成在給你回覆！

2017-09-26 1:09 GMT+08:00 Poga Po <notifications@github.com>:

**Comment by AmberFu** [comment]
Hi Poga,

抱歉，研究了那麼久，卻還沒完成！
目前卡在如果只抓某一日，就必須用迴圈去確認每一頁的日期，效率非常差。

今天剛好有機會問到 PyLadies 的 Mars（她有在社群教爬蟲課程），她說實務上會採定時（每天 or 每小時執行）抓取後存至資料庫，
資料查詢比較快速而且爬蟲也比較有效率。但如果要指定日期，也只能用暴力的的迴圈去掃，效率一定會差。

因此以下兩部份的功能想跟你討論一下：

1. 原本 "輸入日期" 的方式，我想改為輸入 "要抓取的天數" ：
$ python ptt_all_post_v2.py -d 1 -o output_file_name.txt
      -d 1 => 要爬的天數，最多七天（如果設定為 1 ：例如 10/15 03:00 開始抓，只會抓到 10/15 00:00 ）
      -o output_file_name.txt => 輸出的檔案路徑 + 檔名

2. <輸出的檔案路徑> 這部份沒問題，仍以存成檔案為主，目前暫定以 | (pipe) 為區隔。

以上是我目前想法，但還是以你那邊執行端為主，
主要想要確認你打算一天跑幾次（跑的時間大概幾點），或是幾天跑一次？

Best,

Amber

2017-09-26 1:09 GMT+08:00 Poga Po <notifications@github.com>:

**Comment by poga** [comment]
兩個功能聽起來都很不錯 :D

我預計會每天凌晨 03:00 跑一次

**Comment by AmberFu** [comment]
Hi Poga,

功能完成囉！
麻煩執行
​ptt_all_post_v3.py
這個檔案，輸出格式是 "｜" 區隔的 csv
 檔。


語法：   python ptt_all_post_v3.py -d 2 -o ~/output.txt

-d 要抓取的天數，範圍 1~7
-o 輸出的檔案位置與檔名


目前是把
執行過程的提示關掉（不 print 出目前頁數），有時抓取時間比較長，看起來好像沒有在動。

剛剛執行 python ptt_all_post_v3.py -d 1 -o ~/output.txt

，抓今天凌晨到下午五點多的標題大約要十分鐘：
start time:  2017-10-22 17:06:31.157723
end time:  2017-10-22 17:16:49.012393
total cost... 617.85467  sec.


再麻煩你試試囉～

Amber

2017-10-15 22:23 GMT+08:00 Poga Po <notifications@github.com>:

**Comment by poga** [comment]
收到，太棒了 😸 

我回去再試試～（現在人在國外 XD）

**Comment by poga** [comment]
爬下來的已先放在 https://github.com/poga/CivicArchive 。

流程順完後會搬到 g0v 組織下
